const basePccData = {
    "options": [
      {
        "select": "gender",
        "facility": "",
        "listOption": "Male",
        "listValue": "M",
        "optionValuePcc": "M",
        "isDefault": "TRUE"
      },
      {
        "select": "gender",
        "facility": "",
        "listOption": "Female",
        "listValue": "F",
        "optionValuePcc": "F",
        "isDefault": ""
      },
      {
        "select": "gender",
        "facility": "",
        "listOption": "Unknown",
        "listValue": "U",
        "optionValuePcc": "U",
        "isDefault": ""
      },
      {
        "select": "primaryLanguage",
        "facility": "",
        "listOption": "Declined to Specify",
        "listValue": "9899",
        "optionValuePcc": "9899",
        "isDefault": ""
      },
      {
        "select": "primaryLanguage",
        "facility": "",
        "listOption": "English",
        "listValue": "9046",
        "optionValuePcc": "9046",
        "isDefault": "TRUE"
      },
      {
        "select": "primaryLanguage",
        "facility": "",
        "listOption": "Leave Blank",
        "listValue": "0",
        "optionValuePcc": "0",
        "isDefault": ""
      },
      {
        "select": "primaryLanguage",
        "facility": "",
        "listOption": "Spanish",
        "listValue": "39628",
        "optionValuePcc": "39628",
        "isDefault": ""
      },
      {
        "select": "prefix",
        "facility": "",
        "listOption": "Dr.",
        "listValue": "1056",
        "optionValuePcc": "1056",
        "isDefault": ""
      },
      {
        "select": "prefix",
        "facility": "",
        "listOption": "Miss.",
        "listValue": "1057",
        "optionValuePcc": "1057",
        "isDefault": ""
      },
      {
        "select": "prefix",
        "facility": "",
        "listOption": "Mr.",
        "listValue": "1049",
        "optionValuePcc": "1049",
        "isDefault": ""
      },
      {
        "select": "prefix",
        "facility": "",
        "listOption": "Mrs.",
        "listValue": "1050",
        "optionValuePcc": "1050",
        "isDefault": ""
      },
      {
        "select": "prefix",
        "facility": "",
        "listOption": "Ms.",
        "listValue": "1055",
        "optionValuePcc": "1055",
        "isDefault": ""
      },
      {
        "select": "prefix",
        "facility": "",
        "listOption": "Pastor",
        "listValue": "10980",
        "optionValuePcc": "10980",
        "isDefault": ""
      },
      {
        "select": "suffix",
        "facility": "",
        "listOption": "Jr",
        "listValue": "7000",
        "optionValuePcc": "7000",
        "isDefault": ""
      },
      {
        "select": "suffix",
        "facility": "",
        "listOption": "Sr",
        "listValue": "7001",
        "optionValuePcc": "7001",
        "isDefault": ""
      },
      {
        "select": "medicareCoverage",
        "facility": "19",
        "listOption": "Manged",
        "listValue": "3748",
        "optionValuePcc": "3748",
        "isDefault": ""
      },
      {
        "select": "medicareCoverage",
        "facility": "19",
        "listOption": "MSP",
        "listValue": "3758",
        "optionValuePcc": "3758",
        "isDefault": ""
      },
      {
        "select": "medicareCoverage",
        "facility": "19",
        "listOption": "Part A Only",
        "listValue": "3759",
        "optionValuePcc": "3759",
        "isDefault": ""
      },
      {
        "select": "medicareCoverage",
        "facility": "19",
        "listOption": "No Coverage",
        "listValue": "3768",
        "optionValuePcc": "3768",
        "isDefault": ""
      },
      {
        "select": "medicareCoverage",
        "facility": "19",
        "listOption": "Part A & B",
        "listValue": "3778",
        "optionValuePcc": "3778",
        "isDefault": ""
      },
      {
        "select": "medicareCoverage",
        "facility": "19",
        "listOption": "Part A & D",
        "listValue": "3788",
        "optionValuePcc": "3788",
        "isDefault": ""
      },
      {
        "select": "medicareCoverage",
        "facility": "19",
        "listOption": "Part A, B & D",
        "listValue": "3798",
        "optionValuePcc": "3798",
        "isDefault": ""
      },
      {
        "select": "medicareCoverage",
        "facility": "19",
        "listOption": "Part B Only",
        "listValue": "3799",
        "optionValuePcc": "3799",
        "isDefault": ""
      },
      {
        "select": "medicareCoverage",
        "facility": "19",
        "listOption": "Part B & D",
        "listValue": "3808",
        "optionValuePcc": "3808",
        "isDefault": ""
      },
      {
        "select": "defaultPharmacy",
        "facility": "19",
        "listOption": "DISCOVER RX",
        "listValue": "9379",
        "optionValuePcc": "9379",
        "isDefault": ""
      },
      {
        "select": "defaultPharmacy",
        "facility": "19",
        "listOption": "SPECIALTY RX",
        "listValue": "8050",
        "optionValuePcc": "8050",
        "isDefault": "TRUE"
      },
      {
        "select": "defaultPharmacy",
        "facility": "19",
        "listOption": "Speedy Rx",
        "listValue": "9454",
        "optionValuePcc": "9454",
        "isDefault": ""
      }
    ],
    "pccFields": [
      {
        "listName": "residentNumber",
        "facility": "",
        "hidden": "TRUE",
        "DisplayLabel": "",
        "label": "Resident Number",
        "required": "TRUE",
        "DefaultValue": "",
        "min": "",
        "max": "",
        "type": "input",
        "findBy": "selector",
        "id": "",
        "selector": "input[name=\"client_id_number\"]",
        "selector2": ""
      },
      {
        "listName": "medicalRecord",
        "facility": "",
        "hidden": "TRUE",
        "DisplayLabel": "",
        "label": "Medical Record",
        "required": "TRUE",
        "DefaultValue": "",
        "min": "",
        "max": "",
        "type": "input",
        "findBy": "label",
        "id": "",
        "selector": "",
        "selector2": ""
      },
      {
        "listName": "header",
        "facility": "",
        "hidden": "",
        "DisplayLabel": "",
        "label": "Header",
        "required": "TRUE",
        "DefaultValue": "",
        "min": "",
        "max": "",
        "type": "",
        "findBy": "id",
        "id": "#pageHeader",
        "selector": "",
        "selector2": ""
      },
      {
        "listName": "surname",
        "facility": "",
        "hidden": "",
        "DisplayLabel": "Surname",
        "label": "Last Name",
        "required": "TRUE",
        "DefaultValue": "",
        "min": "",
        "max": "",
        "type": "input",
        "findBy": "selector",
        "id": "",
        "selector": "input[name=\"last_name\"]",
        "selector2": ""
      },
      {
        "listName": "firstName",
        "facility": "",
        "hidden": "",
        "DisplayLabel": "First Name",
        "label": "First Name",
        "required": "TRUE",
        "DefaultValue": "",
        "min": "",
        "max": "",
        "type": "input",
        "findBy": "selector",
        "id": "",
        "selector": "input[name=\"first_name\"]",
        "selector2": ""
      },
      {
        "listName": "suffix",
        "facility": "",
        "hidden": "",
        "DisplayLabel": "Suffix",
        "label": "Suffix",
        "required": "TRUE",
        "DefaultValue": "",
        "min": "",
        "max": "",
        "type": "select",
        "findBy": "selector",
        "id": "",
        "selector": "select[name=\"suffix\"]",
        "selector2": ""
      },
      {
        "listName": "prefix",
        "facility": "",
        "hidden": "",
        "DisplayLabel": "Prefix",
        "label": "",
        "required": "",
        "DefaultValue": "",
        "min": "",
        "max": "",
        "type": "select",
        "findBy": "selector",
        "id": "",
        "selector": "select[name=\"preffix\"]",
        "selector2": ""
      },
      {
        "listName": "birthDate",
        "facility": "",
        "hidden": "",
        "DisplayLabel": "",
        "label": "",
        "required": "",
        "DefaultValue": "",
        "min": "",
        "max": "",
        "type": "input",
        "findBy": "selector",
        "id": "",
        "selector": "input[name=\"first_name\"]",
        "selector2": ""
      },
      {
        "listName": "primaryLanguage",
        "facility": "",
        "hidden": "",
        "DisplayLabel": "Primary Language",
        "label": "",
        "required": "",
        "DefaultValue": "39628",
        "min": "",
        "max": "",
        "type": "select",
        "findBy": "selector",
        "id": "",
        "selector": "[name=\"primary_lang_id\"]",
        "selector2": ""
      },
      {
        "listName": "defaultPharmacy",
        "facility": "19",
        "hidden": "TRUE",
        "DisplayLabel": "",
        "label": "",
        "required": "TRUE",
        "DefaultValue": "8050",
        "min": "",
        "max": "",
        "type": "select",
        "findBy": "selector",
        "id": "",
        "selector": "[name=\"pharmacy_id\"]",
        "selector2": ""
      },
      {
        "listName": "alergies",
        "facility": "",
        "hidden": "",
        "DisplayLabel": "Allergies",
        "label": "",
        "required": "",
        "DefaultValue": "",
        "min": "",
        "max": "",
        "type": "",
        "findBy": "",
        "id": "",
        "selector": "",
        "selector2": ""
      },
      {
        "listName": "allergiesBoolean",
        "facility": "",
        "hidden": "",
        "DisplayLabel": "",
        "label": "",
        "required": "",
        "DefaultValue": "",
        "min": "",
        "max": "",
        "type": "",
        "findBy": "",
        "id": "",
        "selector": "",
        "selector2": ""
      },
      {
        "listName": "gender",
        "facility": "",
        "hidden": "",
        "DisplayLabel": "Sex",
        "label": "",
        "required": "",
        "DefaultValue": "",
        "min": "",
        "max": "",
        "type": "",
        "findBy": "",
        "id": "",
        "selector": "select[name=\"sex\"]",
        "selector2": ""
      },
      {
        "listName": "medicareCoverage",
        "facility": "",
        "hidden": "TRUE",
        "DisplayLabel": "",
        "label": "",
        "required": "",
        "DefaultValue": "",
        "min": "",
        "max": "",
        "type": "",
        "findBy": "",
        "id": "",
        "selector": "",
        "selector2": ""
      },
      {
        "listName": "medicareCoverage",
        "facility": "19",
        "hidden": "",
        "DisplayLabel": "Medicare Coverage",
        "label": "Medicare Coverage",
        "required": "TRUE",
        "DefaultValue": "",
        "min": "",
        "max": "",
        "type": "select",
        "findBy": "label",
        "id": "",
        "selector": "",
        "selector2": ""
      },
      {
        "listName": "medicareBenificiaryId",
        "facility": "",
        "hidden": "",
        "DisplayLabel": "Medicare Beneficiary ID",
        "label": "",
        "required": "",
        "DefaultValue": "",
        "min": "",
        "max": "",
        "type": "input",
        "findBy": "selector",
        "id": "",
        "selector": "input[aria-labelledby=\"Medicare_Beneficiary_ID-AriaId\"]",
        "selector2": ""
      },
      {
        "listName": "race",
        "facility": "",
        "hidden": "",
        "DisplayLabel": "Race",
        "label": "Race",
        "required": "",
        "DefaultValue": "",
        "min": "",
        "max": "",
        "type": "input",
        "findBy": "label",
        "id": "",
        "selector": "",
        "selector2": ""
      },
      {
        "listName": "SocialSecurity",
        "facility": "",
        "hidden": "",
        "DisplayLabel": "Social Security #",
        "label": "Social Security",
        "required": "",
        "DefaultValue": "",
        "min": "",
        "max": "",
        "type": "input",
        "findBy": "selector",
        "id": "",
        "selector": "input[aria-labelledby=\"Social_Security_#-AriaId\"]",
        "selector2": ""
      },
      {
        "listName": "ssnRequired",
        "facility": "",
        "hidden": "",
        "DisplayLabel": "SSN Required",
        "label": "",
        "required": "",
        "DefaultValue": "FALSE",
        "min": "",
        "max": "",
        "type": "checkbox",
        "findBy": "",
        "id": "",
        "selector": "",
        "selector2": ""
      },
      {
        "listName": "address",
        "facility": "",
        "hidden": "",
        "DisplayLabel": "Previous address",
        "label": "",
        "required": "",
        "DefaultValue": "",
        "min": "",
        "max": "",
        "type": "input",
        "findBy": "selector",
        "id": "",
        "selector": "input[aria-labelledby=\"address1-AriaId\"]",
        "selector2": ""
      },
      {
        "listName": "zipCode",
        "facility": "",
        "hidden": "",
        "DisplayLabel": "Postal/Zip Code",
        "label": "",
        "required": "",
        "DefaultValue": "",
        "min": "",
        "max": "",
        "type": "input",
        "findBy": "selector",
        "id": "",
        "selector": "input[name=\"postal_zip_code\"]",
        "selector2": ""
      },
      {
        "listName": "city",
        "facility": "",
        "hidden": "",
        "DisplayLabel": "City",
        "label": "",
        "required": "",
        "DefaultValue": "",
        "min": "",
        "max": "",
        "type": "input",
        "findBy": "selector",
        "id": "",
        "selector": "input[name=\"city\"]",
        "selector2": ""
      },
      {
        "listName": "county",
        "facility": "",
        "hidden": "",
        "DisplayLabel": "County",
        "label": "",
        "required": "",
        "DefaultValue": "",
        "min": "",
        "max": "",
        "type": "input",
        "findBy": "selector",
        "id": "",
        "selector": "input[name=\"county\"]",
        "selector2": ""
      },
      {
        "listName": "country",
        "facility": "",
        "hidden": "",
        "DisplayLabel": "Country",
        "label": "",
        "required": "",
        "DefaultValue": "",
        "min": "",
        "max": "",
        "type": "input",
        "findBy": "selector",
        "id": "",
        "selector": "input[name=\"country\"]",
        "selector2": ""
      },
      {
        "listName": "homePhone",
        "facility": "",
        "hidden": "",
        "DisplayLabel": "",
        "label": "",
        "required": "",
        "DefaultValue": "",
        "min": "",
        "max": "",
        "type": "input",
        "findBy": "selector",
        "id": "",
        "selector": "input[name=\"phone_home\"]",
        "selector2": ""
      },
      {
        "listName": "email",
        "facility": "",
        "hidden": "",
        "DisplayLabel": "Home phone",
        "label": "",
        "required": "",
        "DefaultValue": "",
        "min": "",
        "max": "",
        "type": "input",
        "findBy": "selector",
        "id": "",
        "selector": "input[name=\"email_address\"]",
        "selector2": ""
      },
      {
        "listName": "provState",
        "facility": "",
        "hidden": "",
        "DisplayLabel": "Prov/State",
        "label": "",
        "required": "",
        "DefaultValue": "",
        "min": "",
        "max": "",
        "type": "input",
        "findBy": "selector",
        "id": "",
        "selector": "input[aria-labelledby=\"province_state-AriaId\"]",
        "selector2": ""
      },
      {
        "listName": "mobilePhone",
        "facility": "",
        "hidden": "",
        "DisplayLabel": "Mobile phone",
        "label": "",
        "required": "",
        "DefaultValue": "",
        "min": "",
        "max": "",
        "type": "input",
        "findBy": "selector",
        "id": "",
        "selector": "input[name=\"province_state\"]",
        "selector2": ""
      },
      {
        "listName": "",
        "facility": "",
        "hidden": "",
        "DisplayLabel": "",
        "label": "",
        "required": "",
        "DefaultValue": "",
        "min": "",
        "max": "",
        "type": "",
        "findBy": "",
        "id": "",
        "selector": "",
        "selector2": ""
      },
      {
        "listName": "",
        "facility": "",
        "hidden": "",
        "DisplayLabel": "",
        "label": "",
        "required": "",
        "DefaultValue": "",
        "min": "",
        "max": "",
        "type": "",
        "findBy": "",
        "id": "",
        "selector": "",
        "selector2": ""
      },
      {
        "listName": "MO Medicaid",
        "facility": "",
        "hidden": "",
        "DisplayLabel": "",
        "label": "",
        "required": "",
        "DefaultValue": "",
        "min": "",
        "max": "",
        "type": "",
        "findBy": "",
        "id": "",
        "selector": "",
        "selector2": ""
      },
      {
        "listName": "",
        "facility": "",
        "hidden": "",
        "DisplayLabel": "",
        "label": "",
        "required": "",
        "DefaultValue": "",
        "min": "",
        "max": "",
        "type": "",
        "findBy": "",
        "id": "",
        "selector": "",
        "selector2": ""
      },
      {
        "listName": "Primary Medicaid #",
        "facility": "",
        "hidden": "",
        "DisplayLabel": "",
        "label": "",
        "required": "",
        "DefaultValue": "",
        "min": "",
        "max": "",
        "type": "",
        "findBy": "",
        "id": "",
        "selector": "",
        "selector2": ""
      },
      {
        "listName": "Medicare Replacement Name",
        "facility": "",
        "hidden": "",
        "DisplayLabel": "",
        "label": "",
        "required": "",
        "DefaultValue": "",
        "min": "",
        "max": "",
        "type": "",
        "findBy": "",
        "id": "",
        "selector": "",
        "selector2": ""
      },
      {
        "listName": "",
        "facility": "",
        "hidden": "",
        "DisplayLabel": "",
        "label": "",
        "required": "",
        "DefaultValue": "",
        "min": "",
        "max": "",
        "type": "",
        "findBy": "",
        "id": "",
        "selector": "input[name=\"county_id\"]', pccDetails.count",
        "selector2": ""
      },
      {
        "listName": "Medicare Replacement #",
        "facility": "",
        "hidden": "",
        "DisplayLabel": "",
        "label": "",
        "required": "",
        "DefaultValue": "",
        "min": "",
        "max": "",
        "type": "",
        "findBy": "",
        "id": "",
        "selector": "",
        "selector2": ""
      },
      {
        "listName": "",
        "facility": "",
        "hidden": "",
        "DisplayLabel": "",
        "label": "",
        "required": "",
        "DefaultValue": "",
        "min": "",
        "max": "",
        "type": "",
        "findBy": "",
        "id": "",
        "selector": "",
        "selector2": ""
      },
      {
        "listName": "Insurance Name",
        "facility": "",
        "hidden": "",
        "DisplayLabel": "",
        "label": "",
        "required": "",
        "DefaultValue": "",
        "min": "",
        "max": "",
        "type": "",
        "findBy": "",
        "id": "",
        "selector": "",
        "selector2": ""
      },
      {
        "listName": "",
        "facility": "",
        "hidden": "",
        "DisplayLabel": "",
        "label": "",
        "required": "",
        "DefaultValue": "",
        "min": "",
        "max": "",
        "type": "",
        "findBy": "",
        "id": "",
        "selector": "",
        "selector2": ""
      },
      {
        "listName": "Insurance Policy #",
        "facility": "",
        "hidden": "",
        "DisplayLabel": "",
        "label": "",
        "required": "",
        "DefaultValue": "",
        "min": "",
        "max": "",
        "type": "",
        "findBy": "",
        "id": "",
        "selector": "",
        "selector2": ""
      },
      {
        "listName": "Mcr Rplcmt End Date",
        "facility": "",
        "hidden": "",
        "DisplayLabel": "",
        "label": "",
        "required": "",
        "DefaultValue": "",
        "min": "",
        "max": "",
        "type": "",
        "findBy": "",
        "id": "",
        "selector": "",
        "selector2": ""
      },
      {
        "listName": "Policy #",
        "facility": "",
        "hidden": "",
        "DisplayLabel": "",
        "label": "",
        "required": "",
        "DefaultValue": "",
        "min": "",
        "max": "",
        "type": "",
        "findBy": "",
        "id": "",
        "selector": "",
        "selector2": ""
      }
    ]
  };

  
export default basePccData;