const basePccData = {
  "options": [
    {
      "select": "gender",
      "facility": "",
      "listOption": "Male",
      "listValue": "M",
      "optionValuePcc": "M",
      "isDefault": "TRUE",
      "temp": ""
    },
    {
      "select": "gender",
      "facility": "",
      "listOption": "Female",
      "listValue": "F",
      "optionValuePcc": "F",
      "isDefault": "",
      "temp": ""
    },
    {
      "select": "gender",
      "facility": "",
      "listOption": "Unknown",
      "listValue": "U",
      "optionValuePcc": "U",
      "isDefault": "",
      "temp": ""
    },
    {
      "select": "primaryLanguage",
      "facility": "",
      "listOption": "Declined to Specify",
      "listValue": 9758,
      "optionValuePcc": 9758,
      "isDefault": "",
      "temp": ""
    },
    {
      "select": "primaryLanguage",
      "facility": "",
      "listOption": "English",
      "listValue": 9046,
      "optionValuePcc": 9046,
      "isDefault": "TRUE",
      "temp": ""
    },
    {
      "select": "primaryLanguage",
      "facility": "",
      "listOption": "Leave Blank",
      "listValue": 0,
      "optionValuePcc": 0,
      "isDefault": "",
      "temp": ""
    },
    {
      "select": "primaryLanguage",
      "facility": "",
      "listOption": "Spanish",
      "listValue": 42759,
      "optionValuePcc": 42759,
      "isDefault": "",
      "temp": ""
    },
    {
      "select": "prefix",
      "facility": "",
      "listOption": "Dr.",
      "listValue": 1056,
      "optionValuePcc": 1056,
      "isDefault": "",
      "temp": ""
    },
    {
      "select": "prefix",
      "facility": "",
      "listOption": "Miss.",
      "listValue": 1057,
      "optionValuePcc": 1057,
      "isDefault": "",
      "temp": ""
    },
    {
      "select": "prefix",
      "facility": "",
      "listOption": "Mr.",
      "listValue": 1049,
      "optionValuePcc": 1049,
      "isDefault": "",
      "temp": ""
    },
    {
      "select": "prefix",
      "facility": "",
      "listOption": "Mrs.",
      "listValue": 1050,
      "optionValuePcc": 1050,
      "isDefault": "",
      "temp": ""
    },
    {
      "select": "prefix",
      "facility": "",
      "listOption": "Ms.",
      "listValue": 1055,
      "optionValuePcc": 1055,
      "isDefault": "",
      "temp": ""
    },
    {
      "select": "prefix",
      "facility": "",
      "listOption": "Pastor",
      "listValue": 48385,
      "optionValuePcc": 48385,
      "isDefault": "",
      "temp": ""
    },
    {
      "select": "suffix",
      "facility": "",
      "listOption": "Jr",
      "listValue": 7000,
      "optionValuePcc": 7000,
      "isDefault": "",
      "temp": ""
    },
    {
      "select": "suffix",
      "facility": "",
      "listOption": "Sr",
      "listValue": 7001,
      "optionValuePcc": 7001,
      "isDefault": "",
      "temp": ""
    },
    {
      "select": "medicareCoverage",
      "facility": 19,
      "listOption": "",
      "listValue": "-",
      "optionValuePcc": "",
      "isDefault": "",
      "temp": ""
    },
    {
      "select": "medicareCoverage",
      "facility": 19,
      "listOption": "Manged",
      "listValue": "Manged",
      "optionValuePcc": "Manged",
      "isDefault": "",
      "temp": 3748
    },
    {
      "select": "medicareCoverage",
      "facility": 19,
      "listOption": "MSP",
      "listValue": "MSP",
      "optionValuePcc": "MSP",
      "isDefault": "",
      "temp": 3758
    },
    {
      "select": "medicareCoverage",
      "facility": 19,
      "listOption": "Part A Only",
      "listValue": "Part A Only",
      "optionValuePcc": "Part A Only",
      "isDefault": "",
      "temp": 3759
    },
    {
      "select": "medicareCoverage",
      "facility": 19,
      "listOption": "No Coverage",
      "listValue": "No Coverage",
      "optionValuePcc": "No Coverage",
      "isDefault": "",
      "temp": 3768
    },
    {
      "select": "medicareCoverage",
      "facility": 19,
      "listOption": "Part A & B",
      "listValue": "Part A & B",
      "optionValuePcc": "Part A & B",
      "isDefault": "",
      "temp": 3778
    },
    {
      "select": "medicareCoverage",
      "facility": 19,
      "listOption": "Part A & D",
      "listValue": "Part A & D",
      "optionValuePcc": "Part A & D",
      "isDefault": "",
      "temp": 3788
    },
    {
      "select": "medicareCoverage",
      "facility": 19,
      "listOption": "Part A, B & D",
      "listValue": "Part A, B & D",
      "optionValuePcc": "Part A, B & D",
      "isDefault": "",
      "temp": 3798
    },
    {
      "select": "medicareCoverage",
      "facility": 19,
      "listOption": "Part B Only",
      "listValue": "Part B Only",
      "optionValuePcc": "Part B Only",
      "isDefault": "",
      "temp": 3799
    },
    {
      "select": "medicareCoverage",
      "facility": 19,
      "listOption": "Part B & D",
      "listValue": "Part B & D",
      "optionValuePcc": "Part B & D",
      "isDefault": "",
      "temp": 3808
    },
    {
      "select": "defaultPharmacy",
      "facility": 19,
      "listOption": "DISCOVER RX",
      "listValue": 9379,
      "optionValuePcc": 9379,
      "isDefault": "",
      "temp": ""
    },
    {
      "select": "defaultPharmacy",
      "facility": 19,
      "listOption": "SPECIALTY RX",
      "listValue": 8050,
      "optionValuePcc": 8050,
      "isDefault": "TRUE",
      "temp": ""
    },
    {
      "select": "defaultPharmacy",
      "facility": 19,
      "listOption": "Speedy Rx",
      "listValue": 9454,
      "optionValuePcc": 9454,
      "isDefault": "",
      "temp": ""
    },
    {
      "select": "medicareEligibilityType",
      "facility": "",
      "listOption": "Enrolled in Managed Medicare",
      "listValue": "Enrolled in Managed Medicare",
      "optionValuePcc": "",
      "isDefault": "",
      "temp": ""
    },
    {
      "select": "medicareEligibilityType",
      "facility": "",
      "listOption": "No coverage",
      "listValue": "No coverage",
      "optionValuePcc": "",
      "isDefault": "",
      "temp": ""
    },
    {
      "select": "medicareEligibilityType",
      "facility": "",
      "listOption": "Part A & B",
      "listValue": "Part A & B",
      "optionValuePcc": "",
      "isDefault": "",
      "temp": ""
    },
    {
      "select": "medicareEligibilityType",
      "facility": "",
      "listOption": "Part A & D",
      "listValue": "Part A & D",
      "optionValuePcc": "",
      "isDefault": "",
      "temp": ""
    },
    {
      "select": "medicareEligibilityType",
      "facility": "",
      "listOption": "Part A only",
      "listValue": "Part A only",
      "optionValuePcc": "",
      "isDefault": "",
      "temp": ""
    },
    {
      "select": "medicareEligibilityType",
      "facility": "",
      "listOption": "Part A, B & D",
      "listValue": "Part A, B & D",
      "optionValuePcc": "",
      "isDefault": "",
      "temp": ""
    },
    {
      "select": "medicareEligibilityType",
      "facility": "",
      "listOption": "Part B & D only",
      "listValue": "Part B & D only",
      "optionValuePcc": "",
      "isDefault": "",
      "temp": ""
    },
    {
      "select": "medicareEligibilityType",
      "facility": "",
      "listOption": "Part B only",
      "listValue": "Part B only",
      "optionValuePcc": "",
      "isDefault": "",
      "temp": ""
    },
    {
      "select": "medicareEligibilityType",
      "facility": "",
      "listOption": "Part",
      "listValue": "Part",
      "optionValuePcc": "",
      "isDefault": "",
      "temp": ""
    },
    {
      "select": "admissionType",
      "facility": "19",
      "listOption": "HOSPICE",
      "listValue": "HOSPICE",
      "optionValuePcc": "",
      "isDefault": "",
      "temp": ""
    },
    {
      "select": "admissionType",
      "facility": "19",
      "listOption": "LTC",
      "listValue": "LTC",
      "optionValuePcc": "",
      "isDefault": "",
      "temp": ""
    },
    {
      "select": "admissionType",
      "facility": "19",
      "listOption": "RESPITE",
      "listValue": "RESPITE",
      "optionValuePcc": "",
      "isDefault": "",
      "temp": ""
    },
    {
      "select": "admissionType",
      "facility": "19",
      "listOption": "SAR",
      "listValue": "SAR",
      "optionValuePcc": "",
      "isDefault": "",
      "temp": ""
    },
    {
      "select": "admissionType",
      "facility": "19",
      "listOption": "SAR to LT",
      "listValue": "SAR to LT",
      "optionValuePcc": "",
      "isDefault": "",
      "temp": ""
    }
  ],
  "pccFields": [
    {
      "listName": "residentNumber",
      "facility": "",
      "hidden": "TRUE",
      "DisplayLabel": "Resident Number",
      "label": "Resident Number",
      "required": "TRUE",
      "DefaultValue": "",
      "type": "input",
      "findBy": "selector",
      "id": "",
      "selector": "input[name=\"\"client_id_number\"\"]",
      "selector2": "",
      "group": "",
      "order": "",
      "max": ""
    },
    {
      "listName": "medicalRecord",
      "facility": "",
      "hidden": "TRUE",
      "DisplayLabel": "Medical Record",
      "label": "Medical Record",
      "required": "TRUE",
      "DefaultValue": "",
      "type": "input",
      "findBy": "label",
      "id": "",
      "selector": "",
      "selector2": "",
      "group": "",
      "order": "",
      "max": ""
    },
    {
      "listName": "header",
      "facility": "",
      "hidden": "TRUE",
      "DisplayLabel": "Header",
      "label": "Header",
      "required": "TRUE",
      "DefaultValue": "",
      "type": "",
      "findBy": "id",
      "id": "#pageHeader",
      "selector": "",
      "selector2": "",
      "group": "",
      "order": "",
      "max": ""
    },
    {
      "listName": "surname",
      "facility": "",
      "hidden": "",
      "DisplayLabel": "Last Name",
      "label": "Last Name",
      "required": "TRUE",
      "DefaultValue": "",
      "type": "input",
      "findBy": "selector",
      "id": "",
      "selector": "input[name=\"\"last_name\"\"]",
      "selector2": "",
      "group": 1,
      "order": 3,
      "max": ""
    },
    {
      "listName": "title",
      "facility": "",
      "hidden": "TRUE",
      "DisplayLabel": "title",
      "label": "title",
      "required": "TRUE",
      "DefaultValue": "",
      "type": "select",
      "findBy": "selector",
      "id": "",
      "selector": "select[name=\"\"title\"\"]",
      "selector2": "",
      "group": "",
      "order": "",
      "max": ""
    },
    {
      "listName": "firstName",
      "facility": "",
      "hidden": "",
      "DisplayLabel": "First Name",
      "label": "First Name",
      "required": "TRUE",
      "DefaultValue": "",
      "type": "input",
      "findBy": "selector",
      "id": "",
      "selector": "input[name=\"\"first_name\"\"]",
      "selector2": "",
      "group": 1,
      "order": 2,
      "max": ""
    },
    {
      "listName": "suffix",
      "facility": "",
      "hidden": "",
      "DisplayLabel": "Suffix",
      "label": "Suffix",
      "required": "",
      "DefaultValue": "",
      "type": "select",
      "findBy": "selector",
      "id": "",
      "selector": "select[name=\"\"suffix\"\"]",
      "selector2": "",
      "group": 1,
      "order": 4,
      "max": ""
    },
    {
      "listName": "prefix",
      "facility": "",
      "hidden": "",
      "DisplayLabel": "Prefix",
      "label": "",
      "required": "",
      "DefaultValue": "",
      "type": "select",
      "findBy": "",
      "id": "",
      "selector": "",
      "selector2": "",
      "group": 1,
      "order": 1,
      "max": ""
    },
    {
      "listName": "preferredName",
      "facility": "",
      "hidden": "",
      "DisplayLabel": "Preferred Name",
      "label": "Preferred Name",
      "required": "",
      "DefaultValue": "",
      "type": "input",
      "findBy": "selector",
      "id": "",
      "selector": "input[name=\"\"nickname\"\"]",
      "selector2": "",
      "group": 1,
      "order": 5,
      "max": ""
    },
    {
      "listName": "birthDate",
      "facility": "",
      "hidden": "",
      "DisplayLabel": "Birth Date",
      "label": "",
      "required": "",
      "DefaultValue": "",
      "type": "date",
      "findBy": "",
      "id": "",
      "selector": "",
      "selector2": "",
      "group": 1,
      "order": 6,
      "max": ""
    },
    {
      "listName": "mostRecentAdmission",
      "facility": "",
      "hidden": "TRUE",
      "DisplayLabel": "",
      "label": "",
      "required": "",
      "DefaultValue": "",
      "type": "date",
      "findBy": "",
      "id": "",
      "selector": "",
      "selector2": "",
      "group": "",
      "order": "",
      "max": ""
    },
    {
      "listName": "primaryLanguage",
      "facility": "",
      "hidden": "",
      "DisplayLabel": "Primary Language",
      "label": "",
      "required": "",
      "DefaultValue": "",
      "type": "select",
      "findBy": "",
      "id": "",
      "selector": "",
      "selector2": "",
      "group": 1,
      "order": 7,
      "max": ""
    },
    {
      "listName": "defaultPharmacy",
      "facility": "",
      "hidden": "TRUE",
      "DisplayLabel": "",
      "label": "",
      "required": "",
      "DefaultValue": "",
      "type": "input",
      "findBy": "",
      "id": "",
      "selector": "",
      "selector2": "",
      "group": "",
      "order": "",
      "max": ""
    },
    {
      "listName": "alergies",
      "facility": "",
      "hidden": "TRUE",
      "DisplayLabel": "",
      "label": "",
      "required": "",
      "DefaultValue": "",
      "type": "input",
      "findBy": "",
      "id": "",
      "selector": "",
      "selector2": "",
      "group": "",
      "order": "",
      "max": ""
    },
    {
      "listName": "allergiesBoolean",
      "facility": "",
      "hidden": "TRUE",
      "DisplayLabel": "",
      "label": "",
      "required": "",
      "DefaultValue": "",
      "type": "input",
      "findBy": "",
      "id": "",
      "selector": "",
      "selector2": "",
      "group": "",
      "order": "",
      "max": ""
    },
    {
      "listName": "gender",
      "facility": "",
      "hidden": "",
      "DisplayLabel": "Sex",
      "label": "Sex",
      "required": "",
      "DefaultValue": "",
      "type": "select",
      "findBy": "",
      "id": "",
      "selector": "",
      "selector2": "",
      "group": 1,
      "order": 9,
      "max": ""
    },
    {
      "listName": "medicareCoverage",
      "facility": 19,
      "hidden": "",
      "DisplayLabel": "Medicare Coverage",
      "label": "Medicare Coverage",
      "required": "TRUE",
      "DefaultValue": "",
      "type": "select",
      "findBy": "",
      "id": "",
      "selector": "",
      "selector2": "",
      "group": 2,
      "order": 4,
      "max": ""
    },
    {
      "listName": "medicare",
      "facility": "",
      "hidden": "",
      "DisplayLabel": "Medicare #",
      "label": "",
      "required": "",
      "DefaultValue": "",
      "type": "input",
      "findBy": "",
      "id": "",
      "selector": "input[aria-labelledby=\"\"Medicare_(HIC)_#-AriaId\"\"]",
      "selector2": "",
      "group": 2,
      "order": 2,
      "max": 11
    },
    {
      "listName": "medicaid",
      "facility": "",
      "hidden": "",
      "DisplayLabel": "Medicaid #",
      "label": "",
      "required": "",
      "DefaultValue": "",
      "type": "input",
      "findBy": "",
      "id": "",
      "selector": "input[aria-labelledby=\"\"Managed_Medicaid-AriaId\"\"]",
      "selector2": "input[aria-labelledby=\"Medicaid_#-AriaId\"]",
      "group": 2,
      "order": 3,
      "max": 15
    },
    {
      "listName": "medicareSSN",
      "facility": "",
      "hidden": "TRUE",
      "DisplayLabel": "",
      "label": "",
      "required": "",
      "DefaultValue": "",
      "type": "input",
      "findBy": "",
      "id": "",
      "selector": "input[aria-labelledby=\"\"Social_Security_#-AriaId\"\"]",
      "selector2": "",
      "group": "",
      "order": "",
      "max": ""
    },
    {
      "listName": "medicareBenificiaryId",
      "facility": "",
      "hidden": "",
      "DisplayLabel": "Medicare Beneficiary ID",
      "label": "",
      "required": "",
      "DefaultValue": "",
      "type": "input",
      "findBy": "",
      "id": "",
      "selector": "input[aria-labelledby=\"\"Medicare_Beneficiary_ID-AriaId\"\"]",
      "selector2": "",
      "group": 2,
      "order": 1,
      "max": 14
    },
    {
      "listName": "concentVaccine",
      "facility": "",
      "hidden": "",
      "DisplayLabel": "Consent for Flu Vaccine",
      "label": "Consent for Flu Vaccine",
      "required": "TRUE",
      "DefaultValue": "Unknown",
      "type": "",
      "findBy": "label",
      "id": "",
      "selector": "",
      "selector2": "",
      "group": 2,
      "order": "",
      "max": ""
    },
    {
      "listName": "vaccineAuthorization",
      "facility": "",
      "hidden": "",
      "DisplayLabel": "Flu Vaccine Authorization",
      "label": "Flu Vaccine Authorization",
      "required": "TRUE",
      "DefaultValue": "Unknown",
      "type": "",
      "findBy": "label",
      "id": "",
      "selector": "",
      "selector2": "",
      "group": 2,
      "order": "",
      "max": ""
    },
    {
      "listName": "race",
      "facility": "",
      "hidden": "",
      "DisplayLabel": "Race",
      "label": "Race",
      "required": "",
      "DefaultValue": "Unknown",
      "type": "",
      "findBy": "",
      "id": "",
      "selector": "",
      "selector2": "",
      "group": 1,
      "order": 10,
      "max": ""
    },
    {
      "listName": "concentPneumonia",
      "facility": "",
      "hidden": "TRUE",
      "DisplayLabel": "",
      "label": "",
      "required": "TRUE",
      "DefaultValue": "Unknown",
      "type": "",
      "findBy": "",
      "id": "",
      "selector": "",
      "selector2": "",
      "group": 1,
      "order": 15,
      "max": ""
    },
    {
      "listName": "address",
      "facility": "",
      "hidden": "",
      "DisplayLabel": "Previous address",
      "label": "",
      "required": "",
      "DefaultValue": "",
      "type": "",
      "findBy": "",
      "id": "",
      "selector": "",
      "selector2": "",
      "group": 1,
      "order": 16,
      "max": 35
    },
    {
      "listName": "zipCode",
      "facility": "",
      "hidden": "",
      "DisplayLabel": "Postal/Zip Code",
      "label": "",
      "required": "",
      "DefaultValue": "",
      "type": "",
      "findBy": "",
      "id": "",
      "selector": "",
      "selector2": "",
      "group": 1,
      "order": 17,
      "max": ""
    },
    {
      "listName": "city",
      "facility": "",
      "hidden": "",
      "DisplayLabel": "City",
      "label": "",
      "required": "",
      "DefaultValue": "",
      "type": "",
      "findBy": "",
      "id": "",
      "selector": "",
      "selector2": "",
      "group": 1,
      "order": 18,
      "max": ""
    },
    {
      "listName": "county",
      "facility": "",
      "hidden": "",
      "DisplayLabel": "County",
      "label": "",
      "required": "",
      "DefaultValue": "",
      "type": "",
      "findBy": "",
      "id": "",
      "selector": "",
      "selector2": "",
      "group": 1,
      "order": 19,
      "max": ""
    },
    {
      "listName": "country",
      "facility": "",
      "hidden": "",
      "DisplayLabel": "Country",
      "label": "",
      "required": "",
      "DefaultValue": "",
      "type": "",
      "findBy": "",
      "id": "",
      "selector": "",
      "selector2": "",
      "group": 1,
      "order": 20,
      "max": ""
    },
    {
      "listName": "homePhone",
      "facility": "",
      "hidden": "",
      "DisplayLabel": "Phone number",
      "label": "",
      "required": "",
      "DefaultValue": "",
      "type": "",
      "findBy": "",
      "id": "",
      "selector": "",
      "selector2": "",
      "group": 1,
      "order": 22,
      "max": ""
    },
    {
      "listName": "email",
      "facility": "",
      "hidden": "TRUE",
      "DisplayLabel": "",
      "label": "",
      "required": "",
      "DefaultValue": "",
      "type": "",
      "findBy": "",
      "id": "",
      "selector": "",
      "selector2": "",
      "group": "",
      "order": "",
      "max": ""
    },
    {
      "listName": "provState",
      "facility": "",
      "hidden": "",
      "DisplayLabel": "Prov/State",
      "label": "",
      "required": "",
      "DefaultValue": "",
      "type": "",
      "findBy": "",
      "id": "",
      "selector": "",
      "selector2": "",
      "group": 1,
      "order": 21,
      "max": ""
    },
    {
      "listName": "insuranceName",
      "facility": "",
      "hidden": "",
      "DisplayLabel": "Insurance name",
      "label": "",
      "required": "",
      "DefaultValue": "",
      "type": "",
      "findBy": "",
      "id": "",
      "selector": "",
      "selector2": "",
      "group": 2,
      "order": "",
      "max": 25
    },
    {
      "listName": "insuranceNumber",
      "facility": "",
      "hidden": "",
      "DisplayLabel": "Insurance Number",
      "label": "",
      "required": "",
      "DefaultValue": "",
      "type": "",
      "findBy": "",
      "id": "",
      "selector": "",
      "selector2": "",
      "group": 2,
      "order": "",
      "max": 15
    },
    {
      "listName": "socialSecurity",
      "facility": "",
      "hidden": "",
      "DisplayLabel": "Social Security #",
      "label": "Social Security",
      "required": "",
      "DefaultValue": "",
      "type": "input",
      "findBy": "",
      "id": "",
      "selector": "",
      "selector2": "",
      "group": 1,
      "order": 8,
      "max": ""
    },
    {
      "listName": "admissionType",
      "facility": 19,
      "hidden": "",
      "DisplayLabel": "Admission Type",
      "label": "Admission Type",
      "required": "TRUE",
      "DefaultValue": "",
      "type": "select",
      "findBy": "",
      "id": "",
      "selector": "",
      "selector2": "",
      "group": 2,
      "order": "",
      "max": ""
    },
    {
      "listName": "medicareEligibilityType",
      "facility": 12,
      "hidden": "",
      "DisplayLabel": "Medicare Eligibility Type",
      "label": "Medicare Eligibility Type",
      "required": "TRUE",
      "DefaultValue": "",
      "type": "select",
      "findBy": "",
      "id": "",
      "selector": "",
      "selector2": "",
      "group": 2,
      "order": "",
      "max": ""
    }
  ],
  "type": "push"
}


// const basePccData = {
//     "options": [
//       {
//         "select": "gender",
//         "facility": "",
//         "listOption": "Male",
//         "listValue": "M",
//         "optionValuePcc": "M",
//         "isDefault": "TRUE"
//       },
//       {
//         "select": "gender",
//         "facility": "",
//         "listOption": "Female",
//         "listValue": "F",
//         "optionValuePcc": "F",
//         "isDefault": ""
//       },
//       {
//         "select": "gender",
//         "facility": "",
//         "listOption": "Unknown",
//         "listValue": "U",
//         "optionValuePcc": "U",
//         "isDefault": ""
//       },
//       {
//         "select": "primaryLanguage",
//         "facility": "",
//         "listOption": "Declined to Specify",
//         "listValue": "9899",
//         "optionValuePcc": "9899",
//         "isDefault": ""
//       },
//       {
//         "select": "primaryLanguage",
//         "facility": "",
//         "listOption": "English",
//         "listValue": "9046",
//         "optionValuePcc": "9046",
//         "isDefault": "TRUE"
//       },
//       {
//         "select": "primaryLanguage",
//         "facility": "",
//         "listOption": "Leave Blank",
//         "listValue": "0",
//         "optionValuePcc": "0",
//         "isDefault": ""
//       },
//       {
//         "select": "primaryLanguage",
//         "facility": "",
//         "listOption": "Spanish",
//         "listValue": "39628",
//         "optionValuePcc": "39628",
//         "isDefault": ""
//       },
//       {
//         "select": "prefix",
//         "facility": "",
//         "listOption": "Dr.",
//         "listValue": "1056",
//         "optionValuePcc": "1056",
//         "isDefault": ""
//       },
//       {
//         "select": "prefix",
//         "facility": "",
//         "listOption": "Miss.",
//         "listValue": "1057",
//         "optionValuePcc": "1057",
//         "isDefault": ""
//       },
//       {
//         "select": "prefix",
//         "facility": "",
//         "listOption": "Mr.",
//         "listValue": "1049",
//         "optionValuePcc": "1049",
//         "isDefault": ""
//       },
//       {
//         "select": "prefix",
//         "facility": "",
//         "listOption": "Mrs.",
//         "listValue": "1050",
//         "optionValuePcc": "1050",
//         "isDefault": ""
//       },
//       {
//         "select": "prefix",
//         "facility": "",
//         "listOption": "Ms.",
//         "listValue": "1055",
//         "optionValuePcc": "1055",
//         "isDefault": ""
//       },
//       {
//         "select": "prefix",
//         "facility": "",
//         "listOption": "Pastor",
//         "listValue": "10980",
//         "optionValuePcc": "10980",
//         "isDefault": ""
//       },
//       {
//         "select": "suffix",
//         "facility": "",
//         "listOption": "Jr",
//         "listValue": "7000",
//         "optionValuePcc": "7000",
//         "isDefault": ""
//       },
//       {
//         "select": "suffix",
//         "facility": "",
//         "listOption": "Sr",
//         "listValue": "7001",
//         "optionValuePcc": "7001",
//         "isDefault": ""
//       },
//       {
//         "select": "medicareCoverage",
//         "facility": "19",
//         "listOption": "Manged",
//         "listValue": "3748",
//         "optionValuePcc": "3748",
//         "isDefault": ""
//       },
//       {
//         "select": "medicareCoverage",
//         "facility": "19",
//         "listOption": "MSP",
//         "listValue": "3758",
//         "optionValuePcc": "3758",
//         "isDefault": ""
//       },
//       {
//         "select": "medicareCoverage",
//         "facility": "19",
//         "listOption": "Part A Only",
//         "listValue": "3759",
//         "optionValuePcc": "3759",
//         "isDefault": ""
//       },
//       {
//         "select": "medicareCoverage",
//         "facility": "19",
//         "listOption": "No Coverage",
//         "listValue": "3768",
//         "optionValuePcc": "3768",
//         "isDefault": ""
//       },
//       {
//         "select": "medicareCoverage",
//         "facility": "19",
//         "listOption": "Part A & B",
//         "listValue": "3778",
//         "optionValuePcc": "3778",
//         "isDefault": ""
//       },
//       {
//         "select": "medicareCoverage",
//         "facility": "19",
//         "listOption": "Part A & D",
//         "listValue": "3788",
//         "optionValuePcc": "3788",
//         "isDefault": ""
//       },
//       {
//         "select": "medicareCoverage",
//         "facility": "19",
//         "listOption": "Part A, B & D",
//         "listValue": "3798",
//         "optionValuePcc": "3798",
//         "isDefault": ""
//       },
//       {
//         "select": "medicareCoverage",
//         "facility": "19",
//         "listOption": "Part B Only",
//         "listValue": "3799",
//         "optionValuePcc": "3799",
//         "isDefault": ""
//       },
//       {
//         "select": "medicareCoverage",
//         "facility": "19",
//         "listOption": "Part B & D",
//         "listValue": "3808",
//         "optionValuePcc": "3808",
//         "isDefault": ""
//       },
//       {
//         "select": "defaultPharmacy",
//         "facility": "19",
//         "listOption": "DISCOVER RX",
//         "listValue": "9379",
//         "optionValuePcc": "9379",
//         "isDefault": ""
//       },
//       {
//         "select": "defaultPharmacy",
//         "facility": "19",
//         "listOption": "SPECIALTY RX",
//         "listValue": "8050",
//         "optionValuePcc": "8050",
//         "isDefault": "TRUE"
//       },
//       {
//         "select": "defaultPharmacy",
//         "facility": "19",
//         "listOption": "Speedy Rx",
//         "listValue": "9454",
//         "optionValuePcc": "9454",
//         "isDefault": ""
//       }
//     ],
//     "pccFields": [
//       {
//         "listName": "residentNumber",
//         "facility": "",
//         "hidden": "TRUE",
//         "DisplayLabel": "",
//         "label": "Resident Number",
//         "required": "TRUE",
//         "DefaultValue": "",
//         "min": "",
//         "max": "",
//         "type": "input",
//         "findBy": "selector",
//         "id": "",
//         "selector": "input[name=\"client_id_number\"]",
//         "selector2": ""
//       },
//       {
//         "listName": "medicalRecord",
//         "facility": "",
//         "hidden": "TRUE",
//         "DisplayLabel": "",
//         "label": "Medical Record",
//         "required": "TRUE",
//         "DefaultValue": "",
//         "min": "",
//         "max": "",
//         "type": "input",
//         "findBy": "label",
//         "id": "",
//         "selector": "",
//         "selector2": ""
//       },
//       {
//         "listName": "header",
//         "facility": "",
//         "hidden": "",
//         "DisplayLabel": "",
//         "label": "Header",
//         "required": "TRUE",
//         "DefaultValue": "",
//         "min": "",
//         "max": "",
//         "type": "",
//         "findBy": "id",
//         "id": "#pageHeader",
//         "selector": "",
//         "selector2": ""
//       },
//       {
//         "listName": "surname",
//         "facility": "",
//         "hidden": "",
//         "DisplayLabel": "Surname",
//         "label": "Last Name",
//         "required": "TRUE",
//         "DefaultValue": "",
//         "min": "",
//         "max": "",
//         "type": "input",
//         "findBy": "selector",
//         "id": "",
//         "selector": "input[name=\"last_name\"]",
//         "selector2": ""
//       },
//       {
//         "listName": "firstName",
//         "facility": "",
//         "hidden": "",
//         "DisplayLabel": "First Name",
//         "label": "First Name",
//         "required": "TRUE",
//         "DefaultValue": "",
//         "min": "",
//         "max": "",
//         "type": "input",
//         "findBy": "selector",
//         "id": "",
//         "selector": "input[name=\"first_name\"]",
//         "selector2": ""
//       },
//       {
//         "listName": "suffix",
//         "facility": "",
//         "hidden": "",
//         "DisplayLabel": "Suffix",
//         "label": "Suffix",
//         "required": "TRUE",
//         "DefaultValue": "",
//         "min": "",
//         "max": "",
//         "type": "select",
//         "findBy": "selector",
//         "id": "",
//         "selector": "select[name=\"suffix\"]",
//         "selector2": ""
//       },
//       {
//         "listName": "prefix",
//         "facility": "",
//         "hidden": "",
//         "DisplayLabel": "Prefix",
//         "label": "",
//         "required": "",
//         "DefaultValue": "",
//         "min": "",
//         "max": "",
//         "type": "select",
//         "findBy": "selector",
//         "id": "",
//         "selector": "select[name=\"preffix\"]",
//         "selector2": ""
//       },
//       {
//         "listName": "birthDate",
//         "facility": "",
//         "hidden": "",
//         "DisplayLabel": "",
//         "label": "",
//         "required": "",
//         "DefaultValue": "",
//         "min": "",
//         "max": "",
//         "type": "input",
//         "findBy": "selector",
//         "id": "",
//         "selector": "input[name=\"first_name\"]",
//         "selector2": ""
//       },
//       {
//         "listName": "primaryLanguage",
//         "facility": "",
//         "hidden": "",
//         "DisplayLabel": "Primary Language",
//         "label": "",
//         "required": "",
//         "DefaultValue": "39628",
//         "min": "",
//         "max": "",
//         "type": "select",
//         "findBy": "selector",
//         "id": "",
//         "selector": "[name=\"primary_lang_id\"]",
//         "selector2": ""
//       },
//       {
//         "listName": "defaultPharmacy",
//         "facility": "19",
//         "hidden": "TRUE",
//         "DisplayLabel": "",
//         "label": "",
//         "required": "TRUE",
//         "DefaultValue": "8050",
//         "min": "",
//         "max": "",
//         "type": "select",
//         "findBy": "selector",
//         "id": "",
//         "selector": "[name=\"pharmacy_id\"]",
//         "selector2": ""
//       },
//       {
//         "listName": "alergies",
//         "facility": "",
//         "hidden": "",
//         "DisplayLabel": "Allergies",
//         "label": "",
//         "required": "",
//         "DefaultValue": "",
//         "min": "",
//         "max": "",
//         "type": "",
//         "findBy": "",
//         "id": "",
//         "selector": "",
//         "selector2": ""
//       },
//       {
//         "listName": "allergiesBoolean",
//         "facility": "",
//         "hidden": "",
//         "DisplayLabel": "",
//         "label": "",
//         "required": "",
//         "DefaultValue": "",
//         "min": "",
//         "max": "",
//         "type": "",
//         "findBy": "",
//         "id": "",
//         "selector": "",
//         "selector2": ""
//       },
//       {
//         "listName": "gender",
//         "facility": "",
//         "hidden": "",
//         "DisplayLabel": "Sex",
//         "label": "",
//         "required": "",
//         "DefaultValue": "",
//         "min": "",
//         "max": "",
//         "type": "",
//         "findBy": "",
//         "id": "",
//         "selector": "select[name=\"sex\"]",
//         "selector2": ""
//       },
//       {
//         "listName": "medicareCoverage",
//         "facility": "",
//         "hidden": "TRUE",
//         "DisplayLabel": "",
//         "label": "",
//         "required": "",
//         "DefaultValue": "",
//         "min": "",
//         "max": "",
//         "type": "",
//         "findBy": "",
//         "id": "",
//         "selector": "",
//         "selector2": ""
//       },
//       {
//         "listName": "medicareCoverage",
//         "facility": "19",
//         "hidden": "",
//         "DisplayLabel": "Medicare Coverage",
//         "label": "Medicare Coverage",
//         "required": "TRUE",
//         "DefaultValue": "",
//         "min": "",
//         "max": "",
//         "type": "select",
//         "findBy": "label",
//         "id": "",
//         "selector": "",
//         "selector2": ""
//       },
//       {
//         "listName": "medicareBenificiaryId",
//         "facility": "",
//         "hidden": "",
//         "DisplayLabel": "Medicare Beneficiary ID",
//         "label": "",
//         "required": "",
//         "DefaultValue": "",
//         "min": "",
//         "max": "",
//         "type": "input",
//         "findBy": "selector",
//         "id": "",
//         "selector": "input[aria-labelledby=\"Medicare_Beneficiary_ID-AriaId\"]",
//         "selector2": ""
//       },
//       {
//         "listName": "race",
//         "facility": "",
//         "hidden": "",
//         "DisplayLabel": "Race",
//         "label": "Race",
//         "required": "",
//         "DefaultValue": "",
//         "min": "",
//         "max": "",
//         "type": "input",
//         "findBy": "label",
//         "id": "",
//         "selector": "",
//         "selector2": ""
//       },
//       {
//         "listName": "SocialSecurity",
//         "facility": "",
//         "hidden": "",
//         "DisplayLabel": "Social Security #",
//         "label": "Social Security",
//         "required": "",
//         "DefaultValue": "",
//         "min": "",
//         "max": "",
//         "type": "input",
//         "findBy": "selector",
//         "id": "",
//         "selector": "input[aria-labelledby=\"Social_Security_#-AriaId\"]",
//         "selector2": ""
//       },
//       {
//         "listName": "ssnRequired",
//         "facility": "",
//         "hidden": "",
//         "DisplayLabel": "SSN Required",
//         "label": "",
//         "required": "",
//         "DefaultValue": "FALSE",
//         "min": "",
//         "max": "",
//         "type": "checkbox",
//         "findBy": "",
//         "id": "",
//         "selector": "",
//         "selector2": ""
//       },
//       {
//         "listName": "address",
//         "facility": "",
//         "hidden": "",
//         "DisplayLabel": "Previous address",
//         "label": "",
//         "required": "",
//         "DefaultValue": "",
//         "min": "",
//         "max": "",
//         "type": "input",
//         "findBy": "selector",
//         "id": "",
//         "selector": "input[aria-labelledby=\"address1-AriaId\"]",
//         "selector2": ""
//       },
//       {
//         "listName": "zipCode",
//         "facility": "",
//         "hidden": "",
//         "DisplayLabel": "Postal/Zip Code",
//         "label": "",
//         "required": "",
//         "DefaultValue": "",
//         "min": "",
//         "max": "",
//         "type": "input",
//         "findBy": "selector",
//         "id": "",
//         "selector": "input[name=\"postal_zip_code\"]",
//         "selector2": ""
//       },
//       {
//         "listName": "city",
//         "facility": "",
//         "hidden": "",
//         "DisplayLabel": "City",
//         "label": "",
//         "required": "",
//         "DefaultValue": "",
//         "min": "",
//         "max": "",
//         "type": "input",
//         "findBy": "selector",
//         "id": "",
//         "selector": "input[name=\"city\"]",
//         "selector2": ""
//       },
//       {
//         "listName": "county",
//         "facility": "",
//         "hidden": "",
//         "DisplayLabel": "County",
//         "label": "",
//         "required": "",
//         "DefaultValue": "",
//         "min": "",
//         "max": "",
//         "type": "input",
//         "findBy": "selector",
//         "id": "",
//         "selector": "input[name=\"county\"]",
//         "selector2": ""
//       },
//       {
//         "listName": "country",
//         "facility": "",
//         "hidden": "",
//         "DisplayLabel": "Country",
//         "label": "",
//         "required": "",
//         "DefaultValue": "",
//         "min": "",
//         "max": "",
//         "type": "input",
//         "findBy": "selector",
//         "id": "",
//         "selector": "input[name=\"country\"]",
//         "selector2": ""
//       },
//       {
//         "listName": "homePhone",
//         "facility": "",
//         "hidden": "",
//         "DisplayLabel": "",
//         "label": "",
//         "required": "",
//         "DefaultValue": "",
//         "min": "",
//         "max": "",
//         "type": "input",
//         "findBy": "selector",
//         "id": "",
//         "selector": "input[name=\"phone_home\"]",
//         "selector2": ""
//       },
//       {
//         "listName": "email",
//         "facility": "",
//         "hidden": "",
//         "DisplayLabel": "Home phone",
//         "label": "",
//         "required": "",
//         "DefaultValue": "",
//         "min": "",
//         "max": "",
//         "type": "input",
//         "findBy": "selector",
//         "id": "",
//         "selector": "input[name=\"email_address\"]",
//         "selector2": ""
//       },
//       {
//         "listName": "provState",
//         "facility": "",
//         "hidden": "",
//         "DisplayLabel": "Prov/State",
//         "label": "",
//         "required": "",
//         "DefaultValue": "",
//         "min": "",
//         "max": "",
//         "type": "input",
//         "findBy": "selector",
//         "id": "",
//         "selector": "input[aria-labelledby=\"province_state-AriaId\"]",
//         "selector2": ""
//       },
//       {
//         "listName": "mobilePhone",
//         "facility": "",
//         "hidden": "",
//         "DisplayLabel": "Mobile phone",
//         "label": "",
//         "required": "",
//         "DefaultValue": "",
//         "min": "",
//         "max": "",
//         "type": "input",
//         "findBy": "selector",
//         "id": "",
//         "selector": "input[name=\"province_state\"]",
//         "selector2": ""
//       },
//       {
//         "listName": "",
//         "facility": "",
//         "hidden": "",
//         "DisplayLabel": "",
//         "label": "",
//         "required": "",
//         "DefaultValue": "",
//         "min": "",
//         "max": "",
//         "type": "",
//         "findBy": "",
//         "id": "",
//         "selector": "",
//         "selector2": ""
//       },
//       {
//         "listName": "",
//         "facility": "",
//         "hidden": "",
//         "DisplayLabel": "",
//         "label": "",
//         "required": "",
//         "DefaultValue": "",
//         "min": "",
//         "max": "",
//         "type": "",
//         "findBy": "",
//         "id": "",
//         "selector": "",
//         "selector2": ""
//       },
//       {
//         "listName": "MO Medicaid",
//         "facility": "",
//         "hidden": "",
//         "DisplayLabel": "",
//         "label": "",
//         "required": "",
//         "DefaultValue": "",
//         "min": "",
//         "max": "",
//         "type": "",
//         "findBy": "",
//         "id": "",
//         "selector": "",
//         "selector2": ""
//       },
//       {
//         "listName": "",
//         "facility": "",
//         "hidden": "",
//         "DisplayLabel": "",
//         "label": "",
//         "required": "",
//         "DefaultValue": "",
//         "min": "",
//         "max": "",
//         "type": "",
//         "findBy": "",
//         "id": "",
//         "selector": "",
//         "selector2": ""
//       },
//       {
//         "listName": "Primary Medicaid #",
//         "facility": "",
//         "hidden": "",
//         "DisplayLabel": "",
//         "label": "",
//         "required": "",
//         "DefaultValue": "",
//         "min": "",
//         "max": "",
//         "type": "",
//         "findBy": "",
//         "id": "",
//         "selector": "",
//         "selector2": ""
//       },
//       {
//         "listName": "Medicare Replacement Name",
//         "facility": "",
//         "hidden": "",
//         "DisplayLabel": "",
//         "label": "",
//         "required": "",
//         "DefaultValue": "",
//         "min": "",
//         "max": "",
//         "type": "",
//         "findBy": "",
//         "id": "",
//         "selector": "",
//         "selector2": ""
//       },
//       {
//         "listName": "",
//         "facility": "",
//         "hidden": "",
//         "DisplayLabel": "",
//         "label": "",
//         "required": "",
//         "DefaultValue": "",
//         "min": "",
//         "max": "",
//         "type": "",
//         "findBy": "",
//         "id": "",
//         "selector": "input[name=\"county_id\"]', pccDetails.count",
//         "selector2": ""
//       },
//       {
//         "listName": "Medicare Replacement #",
//         "facility": "",
//         "hidden": "",
//         "DisplayLabel": "",
//         "label": "",
//         "required": "",
//         "DefaultValue": "",
//         "min": "",
//         "max": "",
//         "type": "",
//         "findBy": "",
//         "id": "",
//         "selector": "",
//         "selector2": ""
//       },
//       {
//         "listName": "",
//         "facility": "",
//         "hidden": "",
//         "DisplayLabel": "",
//         "label": "",
//         "required": "",
//         "DefaultValue": "",
//         "min": "",
//         "max": "",
//         "type": "",
//         "findBy": "",
//         "id": "",
//         "selector": "",
//         "selector2": ""
//       },
//       {
//         "listName": "Insurance Name",
//         "facility": "",
//         "hidden": "",
//         "DisplayLabel": "",
//         "label": "",
//         "required": "",
//         "DefaultValue": "",
//         "min": "",
//         "max": "",
//         "type": "",
//         "findBy": "",
//         "id": "",
//         "selector": "",
//         "selector2": ""
//       },
//       {
//         "listName": "",
//         "facility": "",
//         "hidden": "",
//         "DisplayLabel": "",
//         "label": "",
//         "required": "",
//         "DefaultValue": "",
//         "min": "",
//         "max": "",
//         "type": "",
//         "findBy": "",
//         "id": "",
//         "selector": "",
//         "selector2": ""
//       },
//       {
//         "listName": "Insurance Policy #",
//         "facility": "",
//         "hidden": "",
//         "DisplayLabel": "",
//         "label": "",
//         "required": "",
//         "DefaultValue": "",
//         "min": "",
//         "max": "",
//         "type": "",
//         "findBy": "",
//         "id": "",
//         "selector": "",
//         "selector2": ""
//       },
//       {
//         "listName": "Mcr Rplcmt End Date",
//         "facility": "",
//         "hidden": "",
//         "DisplayLabel": "",
//         "label": "",
//         "required": "",
//         "DefaultValue": "",
//         "min": "",
//         "max": "",
//         "type": "",
//         "findBy": "",
//         "id": "",
//         "selector": "",
//         "selector2": ""
//       },
//       {
//         "listName": "Policy #",
//         "facility": "",
//         "hidden": "",
//         "DisplayLabel": "",
//         "label": "",
//         "required": "",
//         "DefaultValue": "",
//         "min": "",
//         "max": "",
//         "type": "",
//         "findBy": "",
//         "id": "",
//         "selector": "",
//         "selector2": ""
//       }
//     ]
//   };

  
export default basePccData;